[package]
name = "yasd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.9.2", features = ["macros", "auto-send"] }

reqwest = { version = "0.11.11", features = ["rustls-tls-webpki-roots"] }

rustube = { git = "https://github.com/DCNick3/rustube", rev = "408c2e7bab9209dde42b74aba0d6e730bf073ed1" }

async-trait = "0.1.56"
futures = "0.3.21"
bytes = "1.1.0"
tokio = { version = "1.19.2", features = ["sync", "tracing", "rt", "macros", "fs", "io-util"] }
tokio-util = { version = "0.7.3", features = ["compat", "io-util", "codec"] }
tokio-stream = "0.1.9"
async-stream = "0.3.3"
pin-project-lite = "0.2.9"

# Debug tokio stuff
console-subscriber = "0.1.6"

regex = "1.5.6"
once_cell = "1.12.0"

ffmpeg-next = "5.0.3"

unix-named-pipe = "0.2.0"
tempdir = "0.3.7"
async-process = "1.4.0"
which = "4.2.5"

tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "fmt"] }
anyhow = "1.0.58"

[workspace]
members = [
    "pytube",
]

[patch.crates-io]
sre-engine = { git = "https://github.com/RustPython/sre-engine" }

# those are very slow w/o optimizations
[profile.dev.package.sre-engine]
opt-level = 3
[profile.dev.package.rustpython-vm]
opt-level = 3
[profile.dev.package.rustpython-compiler]
opt-level = 3
[profile.dev.package.rustpython-compiler-core]
opt-level = 3
[profile.dev.package.rustpython-ast]
opt-level = 3
[profile.dev.package.rustpython-parser]
opt-level = 3
[profile.dev.package.rustpython-bytecode]
opt-level = 3
[profile.dev.package.rustpython-pylib]
opt-level = 3
